name: CI for Angular
on: push
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install
        run: npm ci
      - name: run tests
        run: npm run test -- --no-watch --code-coverage --browsers=ChromeHeadlessCI
